//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GOODSMVT_ITEM", Namespace="http://schemas.datacontract.org/2004/07/KonicaMinolta.SAP.Integration.Service")]
    [System.SerializableAttribute()]
    public partial class GOODSMVT_ITEM : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ENTRY_QNTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MATERIALField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PLANTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string STGE_LOCField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ENTRY_QNT {
            get {
                return this.ENTRY_QNTField;
            }
            set {
                if ((object.ReferenceEquals(this.ENTRY_QNTField, value) != true)) {
                    this.ENTRY_QNTField = value;
                    this.RaisePropertyChanged("ENTRY_QNT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MATERIAL {
            get {
                return this.MATERIALField;
            }
            set {
                if ((object.ReferenceEquals(this.MATERIALField, value) != true)) {
                    this.MATERIALField = value;
                    this.RaisePropertyChanged("MATERIAL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PLANT {
            get {
                return this.PLANTField;
            }
            set {
                if ((object.ReferenceEquals(this.PLANTField, value) != true)) {
                    this.PLANTField = value;
                    this.RaisePropertyChanged("PLANT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string STGE_LOC {
            get {
                return this.STGE_LOCField;
            }
            set {
                if ((object.ReferenceEquals(this.STGE_LOCField, value) != true)) {
                    this.STGE_LOCField = value;
                    this.RaisePropertyChanged("STGE_LOC");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TIMETICKETS", Namespace="http://schemas.datacontract.org/2004/07/KonicaMinolta.SAP.Integration.Service")]
    [System.SerializableAttribute()]
    public partial class TIMETICKETS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ACT_WORKField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ACT_WORK_2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CONF_TEXTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EXEC_FIN_DATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EXEC_FIN_TIMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EXEC_START_DATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EXEC_START_TIMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EX_CREATED_BYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EX_CREATED_DATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EX_CREATED_TIMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FIN_CONFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OPERATIONField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ACT_WORK {
            get {
                return this.ACT_WORKField;
            }
            set {
                if ((object.ReferenceEquals(this.ACT_WORKField, value) != true)) {
                    this.ACT_WORKField = value;
                    this.RaisePropertyChanged("ACT_WORK");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ACT_WORK_2 {
            get {
                return this.ACT_WORK_2Field;
            }
            set {
                if ((object.ReferenceEquals(this.ACT_WORK_2Field, value) != true)) {
                    this.ACT_WORK_2Field = value;
                    this.RaisePropertyChanged("ACT_WORK_2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CONF_TEXT {
            get {
                return this.CONF_TEXTField;
            }
            set {
                if ((object.ReferenceEquals(this.CONF_TEXTField, value) != true)) {
                    this.CONF_TEXTField = value;
                    this.RaisePropertyChanged("CONF_TEXT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EXEC_FIN_DATE {
            get {
                return this.EXEC_FIN_DATEField;
            }
            set {
                if ((object.ReferenceEquals(this.EXEC_FIN_DATEField, value) != true)) {
                    this.EXEC_FIN_DATEField = value;
                    this.RaisePropertyChanged("EXEC_FIN_DATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EXEC_FIN_TIME {
            get {
                return this.EXEC_FIN_TIMEField;
            }
            set {
                if ((object.ReferenceEquals(this.EXEC_FIN_TIMEField, value) != true)) {
                    this.EXEC_FIN_TIMEField = value;
                    this.RaisePropertyChanged("EXEC_FIN_TIME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EXEC_START_DATE {
            get {
                return this.EXEC_START_DATEField;
            }
            set {
                if ((object.ReferenceEquals(this.EXEC_START_DATEField, value) != true)) {
                    this.EXEC_START_DATEField = value;
                    this.RaisePropertyChanged("EXEC_START_DATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EXEC_START_TIME {
            get {
                return this.EXEC_START_TIMEField;
            }
            set {
                if ((object.ReferenceEquals(this.EXEC_START_TIMEField, value) != true)) {
                    this.EXEC_START_TIMEField = value;
                    this.RaisePropertyChanged("EXEC_START_TIME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EX_CREATED_BY {
            get {
                return this.EX_CREATED_BYField;
            }
            set {
                if ((object.ReferenceEquals(this.EX_CREATED_BYField, value) != true)) {
                    this.EX_CREATED_BYField = value;
                    this.RaisePropertyChanged("EX_CREATED_BY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EX_CREATED_DATE {
            get {
                return this.EX_CREATED_DATEField;
            }
            set {
                if ((object.ReferenceEquals(this.EX_CREATED_DATEField, value) != true)) {
                    this.EX_CREATED_DATEField = value;
                    this.RaisePropertyChanged("EX_CREATED_DATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EX_CREATED_TIME {
            get {
                return this.EX_CREATED_TIMEField;
            }
            set {
                if ((object.ReferenceEquals(this.EX_CREATED_TIMEField, value) != true)) {
                    this.EX_CREATED_TIMEField = value;
                    this.RaisePropertyChanged("EX_CREATED_TIME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FIN_CONF {
            get {
                return this.FIN_CONFField;
            }
            set {
                if ((object.ReferenceEquals(this.FIN_CONFField, value) != true)) {
                    this.FIN_CONFField = value;
                    this.RaisePropertyChanged("FIN_CONF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OPERATION {
            get {
                return this.OPERATIONField;
            }
            set {
                if ((object.ReferenceEquals(this.OPERATIONField, value) != true)) {
                    this.OPERATIONField = value;
                    this.RaisePropertyChanged("OPERATION");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IMobileService")]
    public interface IMobileService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMobileService/SavePDF", ReplyAction="http://tempuri.org/IMobileService/SavePDFResponse")]
        bool SavePDF(string docbinaryarray, string docname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMobileService/GetPDF", ReplyAction="http://tempuri.org/IMobileService/GetPDFResponse")]
        byte[] GetPDF(string DocumentName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMobileService/doZaBAPI", ReplyAction="http://tempuri.org/IMobileService/doZaBAPIResponse")]
        System.Data.DataSet doZaBAPI(string wsOrderNumber, string wsBWClose, string wsBWOpen, string wsColClose, string wsColOpen, string wsLoginUser, string wsPDFDirectory, string wsCreatedDate, ConsoleApplication1.ServiceReference1.GOODSMVT_ITEM[] wsGoodsMvtItem, ConsoleApplication1.ServiceReference1.TIMETICKETS[] wsTimeTickets);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMobileServiceChannel : ConsoleApplication1.ServiceReference1.IMobileService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MobileServiceClient : System.ServiceModel.ClientBase<ConsoleApplication1.ServiceReference1.IMobileService>, ConsoleApplication1.ServiceReference1.IMobileService {
        
        public MobileServiceClient() {
        }
        
        public MobileServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MobileServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MobileServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MobileServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool SavePDF(string docbinaryarray, string docname) {
            return base.Channel.SavePDF(docbinaryarray, docname);
        }
        
        public byte[] GetPDF(string DocumentName) {
            return base.Channel.GetPDF(DocumentName);
        }
        
        public System.Data.DataSet doZaBAPI(string wsOrderNumber, string wsBWClose, string wsBWOpen, string wsColClose, string wsColOpen, string wsLoginUser, string wsPDFDirectory, string wsCreatedDate, ConsoleApplication1.ServiceReference1.GOODSMVT_ITEM[] wsGoodsMvtItem, ConsoleApplication1.ServiceReference1.TIMETICKETS[] wsTimeTickets) {
            return base.Channel.doZaBAPI(wsOrderNumber, wsBWClose, wsBWOpen, wsColClose, wsColOpen, wsLoginUser, wsPDFDirectory, wsCreatedDate, wsGoodsMvtItem, wsTimeTickets);
        }
    }
}
