//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAP.Integration.Tests.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IMobileService")]
    public interface IMobileService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMobileService/SavePDF", ReplyAction="http://tempuri.org/IMobileService/SavePDFResponse")]
        bool SavePDF(string docbinaryarray, string docname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMobileService/GetPDF", ReplyAction="http://tempuri.org/IMobileService/GetPDFResponse")]
        byte[] GetPDF(string DocumentName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMobileService/doZaBAPI", ReplyAction="http://tempuri.org/IMobileService/doZaBAPIResponse")]
        System.Data.DataSet doZaBAPI(string wsOrderNumber, string wsBWClose, string wsBWOpen, string wsColClose, string wsColOpen, string wsLoginUser, string wsPDFDirectory, string wsCreatedDate, KonicaMinolta.SAP.Integration.Service.GOODSMVT_ITEM[] wsGoodsMvtItem, KonicaMinolta.SAP.Integration.Service.TIMETICKETS[] wsTimeTickets);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMobileServiceChannel : SAP.Integration.Tests.ServiceReference1.IMobileService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MobileServiceClient : System.ServiceModel.ClientBase<SAP.Integration.Tests.ServiceReference1.IMobileService>, SAP.Integration.Tests.ServiceReference1.IMobileService {
        
        public MobileServiceClient() {
        }
        
        public MobileServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MobileServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MobileServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MobileServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool SavePDF(string docbinaryarray, string docname) {
            return base.Channel.SavePDF(docbinaryarray, docname);
        }
        
        public byte[] GetPDF(string DocumentName) {
            return base.Channel.GetPDF(DocumentName);
        }
        
        public System.Data.DataSet doZaBAPI(string wsOrderNumber, string wsBWClose, string wsBWOpen, string wsColClose, string wsColOpen, string wsLoginUser, string wsPDFDirectory, string wsCreatedDate, KonicaMinolta.SAP.Integration.Service.GOODSMVT_ITEM[] wsGoodsMvtItem, KonicaMinolta.SAP.Integration.Service.TIMETICKETS[] wsTimeTickets) {
            return base.Channel.doZaBAPI(wsOrderNumber, wsBWClose, wsBWOpen, wsColClose, wsColOpen, wsLoginUser, wsPDFDirectory, wsCreatedDate, wsGoodsMvtItem, wsTimeTickets);
        }
    }
}
